version: "3.9"
services:
  cli:
    environment:
      XDEBUG_MODE: debug
      XDEBUG_SESSION: PHPSTORM
    build:
      context: .
      dockerfile: .docker/Dockerfile
    working_dir: /Users/max/github/serializer-descriminator-map
    volumes:
      - ./:/Users/max/github/serializer-descriminator-map
      - ./.docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro